//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int trackiingID { get; set; }
        public Nullable<int> bID { get; set; }
        public Nullable<int> diD { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual deliveryMan deliveryMan { get; set; }
    }
}
